@startmindmap
* 算法
** 排序
** 查找
** 递归
** 哈希算法
** 分治算法
** 动态规划
** 贪心算法
** 回溯算法
** 字符串匹配算法
*** 单模式串匹配算法
**** BF算法（Brute Force暴力匹配算法或朴素匹配算法）
**** RK算法（Rabin-Karp，BF升级版）
**** BM算法（Boyer-Moore）
***** 坏字符规则
***** 好后缀规则
**** KMP算法
*** 多模式串匹配算法
**** Trie树
**** AC自动机
@endmindmap